[build]
  publish = "."

[functions]
  directory = "functions"

[[redirects]]
  from = "/favicon.ico"
  to = "/404"
  status = 404

[build]
  command = "netlify-lambda build server.js"
  publish = "."